#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, "../..");

function randHex(bytes = 24) {
  return crypto.randomBytes(bytes).toString("hex");
}

function arg(name, fallback) {
  const pref = `--${name}=`;
  const v = process.argv.find((a) => a.startsWith(pref));
  if (!v) return fallback;
  return v.slice(pref.length);
}

function toWsGatewayUrl(value, fallback = "") {
  const raw = String(value || "").trim();
  if (!raw) return fallback;
  try {
    const parsed = new URL(raw);
    if (parsed.protocol === "https:") parsed.protocol = "wss:";
    else if (parsed.protocol === "http:") parsed.protocol = "ws:";
    else if (parsed.protocol !== "ws:" && parsed.protocol !== "wss:") return fallback;
    parsed.pathname = "/gateway";
    parsed.search = "";
    parsed.hash = "";
    return parsed.toString().replace(/\/$/, "");
  } catch {
    return fallback;
  }
}

function stripAddressBrackets(value) {
  return String(value || "").trim().replace(/^\[(.*)\]$/, "$1");
}

function isLoopbackHostname(hostname) {
  const normalized = stripAddressBrackets(hostname).toLowerCase();
  if (!normalized) return false;
  return normalized === "localhost"
    || normalized === "::1"
    || normalized === "0:0:0:0:0:0:0:1"
    || normalized.startsWith("127.");
}

function isUnspecifiedHostname(hostname) {
  const normalized = stripAddressBrackets(hostname).toLowerCase();
  return normalized === "0.0.0.0" || normalized === "::" || normalized === "";
}

function inferMediasoupAnnouncedAddress(value) {
  const raw = String(value || "").trim();
  if (!raw) return "";
  try {
    const parsed = new URL(raw);
    const hostname = stripAddressBrackets(parsed.hostname);
    if (!hostname || isLoopbackHostname(hostname) || isUnspecifiedHostname(hostname)) return "";
    return hostname;
  } catch {
    return "";
  }
}

const frontendUrl = arg("frontend-url", process.env.VITE_FRONTEND_URL || "https://opencom.online");
const coreUrl = arg("core-url", process.env.VITE_CORE_API_URL || process.env.CORE_ISSUER || "https://api.opencom.online");
const corePort = arg("core-port", "3001");
const nodePort = arg("node-port", "3002");
const nodeServerId = arg("node-server-id", "my-node-1");
const nodeId = arg("node-id", "node-local-1");

const dbCore = arg("core-db", "mysql://ods:ods@localhost:3307/ods_core");
const dbNode = arg("node-db", "mysql://ods:ods@localhost:3308/ods_node");
const redisUrl = arg("redis-url", "redis://localhost:6379");
const publicBaseUrl = arg("node-public-url", `http://localhost:${nodePort}`);
const mediasoupAnnouncedAddress = inferMediasoupAnnouncedAddress(publicBaseUrl);
const officialNodeBaseUrl = arg("official-node-base-url", process.env.VITE_OFFICIAL_NODE_BASE_URL || process.env.OFFICIAL_NODE_BASE_URL || "https://node.opencom.online");
const coreGatewayWsUrl = arg("core-gateway-ws-url", process.env.VITE_GATEWAY_WS_URL || "wss://ws.opencom.online/gateway");
const nodeGatewayWsUrl = arg("node-gateway-ws-url", process.env.VITE_NODE_GATEWAY_WS_URL || toWsGatewayUrl(officialNodeBaseUrl, ""));
const voiceGatewayUrl = arg("voice-gateway-url", process.env.VITE_VOICE_GATEWAY_URL || nodeGatewayWsUrl);
const directNodeWsFallback = arg("direct-node-ws-fallback", process.env.VITE_ENABLE_DIRECT_NODE_WS_FALLBACK || "0");

const accessSecret = randHex(24);
const refreshSecret = randHex(24);
const adminPanelPassword = randHex(12);
const coreNodeSyncSecret = randHex(24);
const kid = `core-${randHex(4)}`;

const { publicKey, privateKey } = crypto.generateKeyPairSync("rsa", { modulusLength: 2048 });
const publicJwk = publicKey.export({ format: "jwk" });
const privateJwk = privateKey.export({ format: "jwk" });
publicJwk.kid = kid;
privateJwk.kid = kid;

const backendEnv = `# AUTO-GENERATED by scripts/generate-env.mjs\n# CORE\nCORE_PORT=${corePort}\nCORE_GATEWAY_HOST=0.0.0.0\nCORE_GATEWAY_PORT=9443\nOFFICIAL_NODE_BASE_URL=${officialNodeBaseUrl}\nOFFICIAL_NODE_SERVER_ID=${nodeServerId}\nCORE_NODE_SYNC_SECRET=${coreNodeSyncSecret}\nPRIVATE_CALLS_GUILD_ID=\nCORE_DATABASE_URL=${dbCore}\nCORE_LOG_LEVEL=warn\nCORE_LOG_DIR=./logs\nCORE_LOG_TO_FILE=1\nCORE_JWT_ACCESS_SECRET=${accessSecret}\nCORE_JWT_REFRESH_SECRET=${refreshSecret}\n\n# Core membership signing (RS256)\nCORE_MEMBERSHIP_PRIVATE_JWK='${JSON.stringify(privateJwk)}'\nCORE_MEMBERSHIP_PUBLIC_JWK='${JSON.stringify(publicJwk)}'\nCORE_ISSUER=${coreUrl}\nADMIN_PANEL_PASSWORD=${adminPanelPassword}\n\n# SERVER NODE\nNODE_PORT=${nodePort}\nNODE_HOST=0.0.0.0\nNODE_DATABASE_URL=${dbNode}\nNODE_ID=${nodeId}\nNODE_SERVER_ID=${nodeServerId}\nCORE_BASE_URL=http://localhost:${corePort}\nCORE_JWKS_URL=http://localhost:${corePort}/v1/jwks\nNODE_SYNC_SECRET=${coreNodeSyncSecret}\nLOG_LEVEL=warn\nLOG_DIR=./logs\nLOG_TO_FILE=1\n\nATTACHMENT_MAX_BYTES=52428800\nATTACHMENT_BOOST_MAX_BYTES=104857600\nATTACHMENT_TTL_DAYS=365\nATTACHMENT_STORAGE_DIR=./data/attachments\nPUBLIC_BASE_URL=${publicBaseUrl}\n\n# mediasoup/networking for provider-hosted nodes\nMEDIASOUP_LISTEN_IP=0.0.0.0\nMEDIASOUP_ANNOUNCED_ADDRESS=${mediasoupAnnouncedAddress}\nMEDIASOUP_ENABLE_UDP=1\nMEDIASOUP_ENABLE_TCP=1\nMEDIASOUP_PREFER_UDP=1\nMEDIASOUP_RTC_MIN_PORT=40000\nMEDIASOUP_RTC_MAX_PORT=40100\n\n# REDIS\nREDIS_URL=${redisUrl}\n\n# STRIPE (optional in local dev)\nSTRIPE_SUCCESS_URL=${frontendUrl}/?billing=success\nSTRIPE_CANCEL_URL=${frontendUrl}/?billing=cancel\nSTRIPE_CUSTOMER_PORTAL_RETURN_URL=${frontendUrl}/\n\n# Auth/email verification\nAUTH_REQUIRE_EMAIL_VERIFICATION=0\nAUTH_EMAIL_VERIFICATION_TOKEN_TTL_MINUTES=60\nAUTH_PASSWORD_RESET_TOKEN_TTL_MINUTES=60\nAPP_BASE_URL=${frontendUrl}\n`;

const frontendEnv = `# AUTO-GENERATED by scripts/generate-env.mjs\nVITE_CORE_API_URL=${coreUrl}\nVITE_FRONTEND_URL=${frontendUrl}\nVITE_OFFICIAL_NODE_BASE_URL=${officialNodeBaseUrl}\nOFFICIAL_NODE_BASE_URL=${officialNodeBaseUrl}\nOFFICIAL_NODE_SERVER_ID=${nodeServerId}\nVITE_GATEWAY_WS_URL=${coreGatewayWsUrl}\nVITE_NODE_GATEWAY_WS_URL=${nodeGatewayWsUrl}\nVITE_VOICE_GATEWAY_URL=${voiceGatewayUrl}\nVITE_ENABLE_DIRECT_NODE_WS_FALLBACK=${directNodeWsFallback}\n`;

fs.writeFileSync(path.join(ROOT, "backend/.env"), backendEnv, "utf8");
fs.writeFileSync(path.join(ROOT, "frontend/.env"), frontendEnv, "utf8");

console.log("Generated backend/.env and frontend/.env");
console.log(`CORE_JWT_ACCESS_SECRET=${accessSecret}`);
console.log(`CORE_JWT_REFRESH_SECRET=${refreshSecret}`);
console.log(`ADMIN_PANEL_PASSWORD=${adminPanelPassword}`);
console.log(`CORE_NODE_SYNC_SECRET=${coreNodeSyncSecret}`);
console.log(`CORE_MEMBERSHIP_KID=${kid}`);
