#!/usr/bin/env node
import fs from "node:fs";
import path from "node:path";
import crypto from "node:crypto";
import { fileURLToPath } from "node:url";

const SCRIPT_DIR = path.dirname(fileURLToPath(import.meta.url));
const ROOT = path.resolve(SCRIPT_DIR, "../..");

function randHex(bytes = 24) {
  return crypto.randomBytes(bytes).toString("hex");
}

function arg(name, fallback) {
  const pref = `--${name}=`;
  const v = process.argv.find((a) => a.startsWith(pref));
  if (!v) return fallback;
  return v.slice(pref.length);
}

function toWsGatewayUrl(value, fallback = "") {
  const raw = String(value || "").trim();
  if (!raw) return fallback;
  try {
    const parsed = new URL(raw);
    if (parsed.protocol === "https:") parsed.protocol = "wss:";
    else if (parsed.protocol === "http:") parsed.protocol = "ws:";
    else if (parsed.protocol !== "ws:" && parsed.protocol !== "wss:") return fallback;
    parsed.pathname = "/gateway";
    parsed.search = "";
    parsed.hash = "";
    return parsed.toString().replace(/\/$/, "");
  } catch {
    return fallback;
  }
}

const frontendUrl = arg("frontend-url", process.env.VITE_FRONTEND_URL || "https://opencom.online");
const coreUrl = arg("core-url", process.env.VITE_CORE_API_URL || process.env.CORE_ISSUER || "https://api.opencom.online");
const corePort = arg("core-port", "3001");
const nodePort = arg("node-port", "3002");
const nodeServerId = arg("node-server-id", "my-node-1");
const nodeId = arg("node-id", "node-local-1");

const dbCore = arg("core-db", "mysql://ods:ods@localhost:3307/ods_core");
const dbNode = arg("node-db", "mysql://ods:ods@localhost:3308/ods_node");
const redisUrl = arg("redis-url", "redis://localhost:6379");
const publicBaseUrl = arg("node-public-url", `http://localhost:${nodePort}`);
const officialNodeBaseUrl = arg("official-node-base-url", process.env.VITE_OFFICIAL_NODE_BASE_URL || process.env.OFFICIAL_NODE_BASE_URL || "https://node.opencom.online");
const coreGatewayWsUrl = arg("core-gateway-ws-url", process.env.VITE_GATEWAY_WS_URL || "wss://ws.opencom.online/gateway");
const nodeGatewayWsUrl = arg("node-gateway-ws-url", process.env.VITE_NODE_GATEWAY_WS_URL || toWsGatewayUrl(officialNodeBaseUrl, ""));
const voiceGatewayUrl = arg("voice-gateway-url", process.env.VITE_VOICE_GATEWAY_URL || nodeGatewayWsUrl);
const directNodeWsFallback = arg("direct-node-ws-fallback", process.env.VITE_ENABLE_DIRECT_NODE_WS_FALLBACK || "0");

const accessSecret = randHex(24);
const refreshSecret = randHex(24);
const adminPanelPassword = randHex(12);
const kid = `core-${randHex(4)}`;

const { publicKey, privateKey } = crypto.generateKeyPairSync("rsa", { modulusLength: 2048 });
const publicJwk = publicKey.export({ format: "jwk" });
const privateJwk = privateKey.export({ format: "jwk" });
publicJwk.kid = kid;
privateJwk.kid = kid;

const backendEnv = `# AUTO-GENERATED by scripts/generate-env.mjs\n# CORE\nCORE_PORT=${corePort}\nCORE_DATABASE_URL=${dbCore}\nCORE_JWT_ACCESS_SECRET=${accessSecret}\nCORE_JWT_REFRESH_SECRET=${refreshSecret}\n\n# Core membership signing (RS256)\nCORE_MEMBERSHIP_PRIVATE_JWK='${JSON.stringify(privateJwk)}'\nCORE_MEMBERSHIP_PUBLIC_JWK='${JSON.stringify(publicJwk)}'\nCORE_ISSUER=${coreUrl}\nADMIN_PANEL_PASSWORD=${adminPanelPassword}\n\n# SERVER NODE\nNODE_PORT=${nodePort}\nNODE_DATABASE_URL=${dbNode}\nNODE_ID=${nodeId}\nNODE_SERVER_ID=${nodeServerId}\nCORE_BASE_URL=http://localhost:${corePort}\nCORE_JWKS_URL=http://localhost:${corePort}/v1/jwks\n\nATTACHMENT_MAX_BYTES=52428800\nATTACHMENT_TTL_DAYS=365\nATTACHMENT_STORAGE_DIR=./data/attachments\nPUBLIC_BASE_URL=${publicBaseUrl}\n\n# mediasoup/networking for provider-hosted nodes\nMEDIASOUP_LISTEN_IP=0.0.0.0\nMEDIASOUP_ANNOUNCED_IP=\nMEDIASOUP_RTC_MIN_PORT=40000\nMEDIASOUP_RTC_MAX_PORT=40100\n\n# REDIS\nREDIS_URL=${redisUrl}\n`;

const frontendEnv = `# AUTO-GENERATED by scripts/generate-env.mjs\nVITE_CORE_API_URL=${coreUrl}\nVITE_FRONTEND_URL=${frontendUrl}\nVITE_OFFICIAL_NODE_BASE_URL=${officialNodeBaseUrl}\nOFFICIAL_NODE_BASE_URL=${officialNodeBaseUrl}\nOFFICIAL_NODE_SERVER_ID=${nodeServerId}\nVITE_GATEWAY_WS_URL=${coreGatewayWsUrl}\nVITE_NODE_GATEWAY_WS_URL=${nodeGatewayWsUrl}\nVITE_VOICE_GATEWAY_URL=${voiceGatewayUrl}\nVITE_ENABLE_DIRECT_NODE_WS_FALLBACK=${directNodeWsFallback}\n`;

fs.writeFileSync(path.join(ROOT, "backend/.env"), backendEnv, "utf8");
fs.writeFileSync(path.join(ROOT, "frontend/.env"), frontendEnv, "utf8");

console.log("Generated backend/.env and frontend/.env");
console.log(`CORE_JWT_ACCESS_SECRET=${accessSecret}`);
console.log(`CORE_JWT_REFRESH_SECRET=${refreshSecret}`);
console.log(`ADMIN_PANEL_PASSWORD=${adminPanelPassword}`);
console.log(`CORE_MEMBERSHIP_KID=${kid}`);
