import { spawnSync } from "node:child_process";
import fs from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import {
  clientDir,
  distDir,
  linuxReleaseManifestPath,
  loadClientPackageMetadata,
  loadLinuxPackagingConfig,
  writeLinuxReleaseManifest
} from "./release-manifest.mjs";

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function bashQuote(value) {
  return `'${String(value || "").replace(/'/g, `'\\''`)}'`;
}

function renderBashArray(values) {
  const items = (values || []).map((value) => `  ${bashQuote(value)}`);
  return `(\n${items.join("\n")}\n)`;
}

function renderDesktopFile({ packaging, pkg }) {
  const categories = Array.isArray(packaging.categories)
    ? `${packaging.categories.join(";")};`
    : "Network;";

  return `[Desktop Entry]
Name=${packaging.desktopName || "OpenCom"}
Comment=${pkg.description || "Desktop wrapper for OpenCom"}
Exec=${packaging.commandName || "opencom"} %U
Terminal=false
Type=Application
Icon=${path.parse(packaging.iconFileName || "opencom.png").name}
Categories=${categories}
StartupWMClass=${packaging.desktopStartupWMClass || packaging.desktopName || "OpenCom"}
`;
}

function renderPkgbuild({ packaging, pkg, manifest }) {
  const sourceUrl = manifest.aur?.sourceUrl || "";
  if (!sourceUrl) {
    throw new Error(
      "AUR source URL is empty. Set packaging/linux.json releaseBaseUrl before generating PKGBUILD.",
    );
  }

  const tarballFileName = manifest.aur?.tarballFileName || "OpenCom.tar.gz";
  const iconFileName = packaging.iconFileName || "opencom.png";
  const desktopFileName = packaging.desktopFileName || "opencom.desktop";
  const extractDir = path.parse(tarballFileName).name === "OpenCom.tar"
    ? "OpenCom"
    : "OpenCom";

  const sourceEntries = [
    `${tarballFileName}::${sourceUrl}`,
    desktopFileName,
    iconFileName
  ];
  const shaEntries = [
    manifest.aur?.tarballSha256 || "SKIP",
    "SKIP",
    "SKIP"
  ];

  const lines = [
    "# Maintainer: OpenCom Release Automation <don@opencom.online>",
    "# Generated by client/scripts/build-aur.mjs",
    `pkgname=${packaging.aurPackageName || "opencom-bin"}`,
    `pkgver=${pkg.version}`,
    `pkgrel=${Number(packaging.aurPackageRelease || 1)}`,
    `pkgdesc=${bashQuote(pkg.description || "Desktop wrapper for OpenCom")}`,
    `arch=${renderBashArray(packaging.architectures || ["x86_64"])}`,
    `url=${bashQuote(pkg.homepage || "https://opencom.online")}`,
    `license=${renderBashArray(packaging.licenses || ["GPL3"])}`,
    `depends=${renderBashArray(packaging.runtimeDependencies || [])}`,
  ];

  if (Array.isArray(packaging.optionalDependencies) && packaging.optionalDependencies.length) {
    lines.push(
      `optdepends=${renderBashArray(
        packaging.optionalDependencies.map(
          (item) => `${item.name}: ${item.description}`,
        ),
      )}`,
    );
  }

  if (Array.isArray(packaging.provides) && packaging.provides.length) {
    lines.push(`provides=${renderBashArray(packaging.provides)}`);
  }
  if (Array.isArray(packaging.conflicts) && packaging.conflicts.length) {
    lines.push(`conflicts=${renderBashArray(packaging.conflicts)}`);
  }

  lines.push(`source=${renderBashArray(sourceEntries)}`);
  lines.push(`sha256sums=${renderBashArray(shaEntries)}`);
  lines.push("");
  lines.push("package() {");
  lines.push(
    `  install -dm755 "$pkgdir/opt/${packaging.installDirName || "opencom"}"`,
  );
  lines.push(
    `  cp -a "$srcdir/${extractDir}/." "$pkgdir/opt/${packaging.installDirName || "opencom"}/"`,
  );
  lines.push('  install -dm755 "$pkgdir/usr/bin"');
  lines.push(
    `  ln -sf "/opt/${packaging.installDirName || "opencom"}/${packaging.binaryName || "opencom-client"}" "$pkgdir/usr/bin/${packaging.commandName || "opencom"}"`,
  );
  lines.push(
    `  install -Dm644 "$srcdir/${desktopFileName}" "$pkgdir/usr/share/applications/${desktopFileName}"`,
  );
  lines.push(
    `  install -Dm644 "$srcdir/${iconFileName}" "$pkgdir/usr/share/pixmaps/${iconFileName}"`,
  );
  lines.push("}");

  return `${lines.join("\n")}\n`;
}

function renderSrcInfo({ packaging, pkg, manifest }) {
  const sourceUrl = manifest.aur?.sourceUrl || "";
  const tarballFileName = manifest.aur?.tarballFileName || "OpenCom.tar.gz";
  const iconFileName = packaging.iconFileName || "opencom.png";
  const desktopFileName = packaging.desktopFileName || "opencom.desktop";
  const lines = [
    `pkgbase = ${packaging.aurPackageName || "opencom-bin"}`,
    `\tpkgdesc = ${pkg.description || "Desktop wrapper for OpenCom"}`,
    `\tpkgver = ${pkg.version}`,
    `\tpkgrel = ${Number(packaging.aurPackageRelease || 1)}`,
    `\turl = ${pkg.homepage || "https://opencom.online"}`,
  ];

  for (const item of packaging.architectures || ["x86_64"]) lines.push(`\tarch = ${item}`);
  for (const item of packaging.licenses || ["GPL3"]) lines.push(`\tlicense = ${item}`);
  for (const item of packaging.runtimeDependencies || []) lines.push(`\tdepends = ${item}`);
  for (const item of packaging.optionalDependencies || []) {
    lines.push(`\toptdepends = ${item.name}: ${item.description}`);
  }
  for (const item of packaging.provides || []) lines.push(`\tprovides = ${item}`);
  for (const item of packaging.conflicts || []) lines.push(`\tconflicts = ${item}`);
  lines.push(`\tsource = ${tarballFileName}::${sourceUrl}`);
  lines.push(`\tsource = ${desktopFileName}`);
  lines.push(`\tsource = ${iconFileName}`);
  lines.push(`\tsha256sums = ${manifest.aur?.tarballSha256 || "SKIP"}`);
  lines.push("\tsha256sums = SKIP");
  lines.push("\tsha256sums = SKIP");
  lines.push("");
  lines.push(`pkgname = ${packaging.aurPackageName || "opencom-bin"}`);
  return `${lines.join("\n")}\n`;
}

async function fileExists(targetPath) {
  try {
    await fs.access(targetPath);
    return true;
  } catch {
    return false;
  }
}

function tryRenderSrcInfoWithMakepkg(outputDir) {
  const result = spawnSync("makepkg", ["--printsrcinfo"], {
    cwd: outputDir,
    encoding: "utf8"
  });
  if (result.status !== 0) return "";
  return String(result.stdout || "");
}

async function main() {
  const [packaging, pkg] = await Promise.all([
    loadLinuxPackagingConfig(),
    loadClientPackageMetadata()
  ]);

  let manifest;
  if (await fileExists(linuxReleaseManifestPath)) {
    const raw = await fs.readFile(linuxReleaseManifestPath, "utf8");
    manifest = JSON.parse(raw);
  } else {
    manifest = await writeLinuxReleaseManifest();
  }

  const outputDir = path.join(
    distDir,
    "aur",
    packaging.aurPackageName || "opencom-bin",
  );
  await fs.mkdir(outputDir, { recursive: true });

  const desktopFilePath = path.join(
    outputDir,
    packaging.desktopFileName || "opencom.desktop",
  );
  const iconTargetPath = path.join(
    outputDir,
    packaging.iconFileName || "opencom.png",
  );
  const pkgbuildPath = path.join(outputDir, "PKGBUILD");
  const srcInfoPath = path.join(outputDir, ".SRCINFO");
  const iconSourcePath = path.resolve(clientDir, packaging.iconSource || "src/web/logo.png");

  await fs.writeFile(
    desktopFilePath,
    renderDesktopFile({ packaging, pkg }),
    "utf8",
  );
  await fs.copyFile(iconSourcePath, iconTargetPath);
  await fs.writeFile(
    pkgbuildPath,
    renderPkgbuild({ packaging, pkg, manifest }),
    "utf8",
  );
  const renderedSrcInfo =
    tryRenderSrcInfoWithMakepkg(outputDir) ||
    renderSrcInfo({ packaging, pkg, manifest });
  await fs.writeFile(
    srcInfoPath,
    renderedSrcInfo,
    "utf8",
  );

  console.log(`Generated AUR skeleton in ${path.relative(clientDir, outputDir)}`);
}

main().catch((error) => {
  console.error(error?.message || error);
  process.exit(1);
});
