#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
JOB_MARKER="# opencom-auto-backup"
ENV_FILE="$ROOT_DIR/backups/.env"

MINUTE=0
LOG_FILE="$ROOT_DIR/backups/auto-backup.log"

print_usage() {
  cat <<'USAGE'
Usage:
  ./scripts/ops/backup-cron.sh install
  ./scripts/ops/backup-cron.sh uninstall
  ./scripts/ops/backup-cron.sh status
  ./scripts/ops/backup-cron.sh run-now
USAGE
}

get_current_crontab() {
  crontab -l 2>/dev/null || true
}

remove_existing_job() {
  local content="$1"
  printf '%s\n' "$content" | grep -Fv "$JOB_MARKER" || true
}

generate_env_file() {
  if [[ -f "$ENV_FILE" ]]; then
    echo "Using existing $ENV_FILE"
    return
  fi

  mkdir -p "$(dirname "$ENV_FILE")"

  cat > "$ENV_FILE" <<EOF
# Auto-generated by backup-cron.sh
# Database credentials are loaded separately from $ROOT_DIR/backend/.env.

S3_BUCKET=opencom-backup
S3_PREFIX=auto
AWS_REGION=eu-north-1

BACKUP_KEEP=56
BACKUP_DIR=$ROOT_DIR/backups/auto
EOF

  echo "Generated $ENV_FILE (edit if needed)"
}

build_cron_line() {
  local q_root q_script q_log
  printf -v q_root '%q' "$ROOT_DIR"
  printf -v q_script '%q' "$ROOT_DIR/scripts/ops/auto-backup.sh"
  printf -v q_log '%q' "$LOG_FILE"

  printf '%s */6 * * * cd %s && %s >> %s 2>&1 %s\n' \
    "$MINUTE" "$q_root" "$q_script" "$q_log" "$JOB_MARKER"
}

install_cron_job() {
  generate_env_file

  mkdir -p "$ROOT_DIR/backups"

  local current cleaned line
  current="$(get_current_crontab)"
  cleaned="$(remove_existing_job "$current")"
  line="$(build_cron_line)"

  {
    [[ -n "$cleaned" ]] && printf '%s\n' "$cleaned"
    printf '%s\n' "$line"
  } | crontab -

  echo "Installed cron job:"
  echo "$line"
}

uninstall_cron_job() {
  local current cleaned
  current="$(get_current_crontab)"
  cleaned="$(remove_existing_job "$current")"

  printf '%s\n' "$cleaned" | crontab -
  echo "Removed backup cron job."
}

show_status() {
  local current
  current="$(get_current_crontab)"

  if printf '%s\n' "$current" | grep -Fq "$JOB_MARKER"; then
    printf '%s\n' "$current" | grep -F "$JOB_MARKER"
  else
    echo "No OpenCom backup cron job found."
  fi
}

run_now() {
  "$ROOT_DIR/scripts/ops/auto-backup.sh"
}

main() {
  local command="${1:-}"

  case "$command" in
    install) install_cron_job ;;
    uninstall) uninstall_cron_job ;;
    status) show_status ;;
    run-now) run_now ;;
    -h|--help|help|"") print_usage ;;
    *)
      echo "Unknown command: $command"
      print_usage
      exit 1
      ;;
  esac
}

main "$@"
