ALTER TABLE users
  ADD COLUMN IF NOT EXISTS display_name VARCHAR(64),
  ADD COLUMN IF NOT EXISTS bio VARCHAR(400),
  ADD COLUMN IF NOT EXISTS pfp_url TEXT,
  ADD COLUMN IF NOT EXISTS banner_url TEXT;

CREATE TABLE IF NOT EXISTS user_badges (
  user_id VARCHAR(64) NOT NULL,
  badge VARCHAR(64) NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (user_id, badge),
  CONSTRAINT fk_badges_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS presence (
  user_id VARCHAR(64) PRIMARY KEY,
  status VARCHAR(16) NOT NULL,
  custom_status VARCHAR(128),
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_presence_user FOREIGN KEY (user_id) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS invites (
  code VARCHAR(32) PRIMARY KEY,
  server_id VARCHAR(64) NOT NULL,
  created_by VARCHAR(64) NOT NULL,
  max_uses INT NULL,
  uses INT NOT NULL DEFAULT 0,
  expires_at TIMESTAMP NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  CONSTRAINT fk_inv_server FOREIGN KEY (server_id) REFERENCES servers(id) ON DELETE CASCADE,
  CONSTRAINT fk_inv_user FOREIGN KEY (created_by) REFERENCES users(id) ON DELETE CASCADE
);
