CREATE TABLE IF NOT EXISTS boost_gifts (
  id VARCHAR(32) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NOT NULL,
  code VARCHAR(96) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NOT NULL,
  purchaser_user_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NOT NULL,
  recipient_user_id VARCHAR(64) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NULL,
  status ENUM('pending_payment','active','redeemed','expired','void') NOT NULL DEFAULT 'pending_payment',
  stripe_checkout_session_id VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NULL,
  stripe_payment_intent_id VARCHAR(128) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NULL,
  amount_pence INT UNSIGNED NOT NULL DEFAULT 1000,
  currency VARCHAR(8) CHARACTER SET utf8mb4 COLLATE utf8mb4_uca1400_ai_ci NOT NULL DEFAULT 'gbp',
  grant_days INT UNSIGNED NOT NULL DEFAULT 30,
  purchased_at DATETIME NULL,
  expires_at DATETIME NOT NULL,
  redeemed_at DATETIME NULL,
  created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  updated_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (id),
  UNIQUE KEY uniq_boost_gifts_code (code),
  UNIQUE KEY uniq_boost_gifts_checkout (stripe_checkout_session_id),
  INDEX idx_boost_gifts_purchaser (purchaser_user_id, created_at),
  INDEX idx_boost_gifts_status (status, expires_at),
  CONSTRAINT fk_boost_gifts_purchaser FOREIGN KEY (purchaser_user_id) REFERENCES users(id) ON DELETE CASCADE,
  CONSTRAINT fk_boost_gifts_recipient FOREIGN KEY (recipient_user_id) REFERENCES users(id) ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_uca1400_ai_ci;
