#!/usr/bin/env node
/**
 * Generates nginx config and self-signed TLS certs for Core API (HTTP + WSS /gateway)
 * and Official Server Node (HTTP + WSS /gateway).
 *
 * Usage:
 *   node scripts/generate-nginx.mjs [options]
 *
 * Options:
 *   --core-domain=api.example.com   Hostname for core API (default: core.opencom.local)
 *   --node-domain=node.example.com  Hostname for official server node (default: node.opencom.local)
 *   --core-port=3001                Backend port for core (default: 3001)
 *   --node-port=3002                Backend port for node (default: 3002)
 *   --certs-dir=./certs             Where to write certs (default: ./certs)
 *   --output=nginx-opencom.conf      Nginx config output path (default: nginx-opencom.conf in project root)
 *   --certs-only                    Only generate certs, do not write nginx config
 *   --nginx-only                    Only write nginx config (use existing certs)
 */

import fs from "node:fs";
import path from "node:path";
import { execSync } from "node:child_process";

const ROOT = path.resolve(path.dirname(new URL(import.meta.url).pathname), "..");

function arg(name, fallback) {
  const pref = `--${name}=`;
  const v = process.argv.find((a) => a.startsWith(pref));
  if (!v) return fallback;
  return v.slice(pref.length);
}

function flag(name) {
  return process.argv.includes(`--${name}`);
}

const coreDomain = arg("core-domain", "core.opencom.local");
const nodeDomain = arg("node-domain", "node.opencom.local");
const corePort = arg("core-port", "3001");
const nodePort = arg("node-port", "3002");
const certsDir = path.resolve(ROOT, arg("certs-dir", "certs"));
const outputPath = path.resolve(ROOT, arg("output", "nginx-opencom.conf"));
const certsOnly = flag("certs-only");
const nginxOnly = flag("nginx-only");

function ensureDir(dir) {
  if (!fs.existsSync(dir)) fs.mkdirSync(dir, { recursive: true });
}

function generateSelfSignedCert(domain, keyPath, certPath) {
  const key = path.join(certsDir, keyPath);
  const cert = path.join(certsDir, certPath);
  if (fs.existsSync(key) && fs.existsSync(cert) && nginxOnly) return;
  ensureDir(path.dirname(key));
  const subj = `/O=OpenCom/CN=${domain}`;
  execSync(
    `openssl req -x509 -nodes -days 3650 -newkey rsa:2048 -keyout "${key}" -out "${cert}" -subj "${subj}"`,
    { stdio: "inherit" }
  );
  console.log(`[generate-nginx] Created ${key} and ${cert} for ${domain}`);
}

function generateCerts() {
  if (nginxOnly) return;
  ensureDir(certsDir);
  generateSelfSignedCert(coreDomain, "core.key", "core.crt");
  generateSelfSignedCert(nodeDomain, "node.key", "node.crt");
}

function nginxConfig() {
  const coreKey = path.resolve(certsDir, "core.key");
  const coreCrt = path.resolve(certsDir, "core.crt");
  const nodeKey = path.resolve(certsDir, "node.key");
  const nodeCrt = path.resolve(certsDir, "node.crt");

  return `# Generated by scripts/generate-nginx.mjs for OpenCom
# Core API + WebSocket /gateway; Official Server Node + WebSocket /gateway
# Use with self-signed certs in ${path.relative(ROOT, certsDir)}/

upstream opencom_core {
    server 127.0.0.1:${corePort};
}

upstream opencom_node {
    server 127.0.0.1:${nodePort};
}

# Core API (REST + WSS /gateway)
server {
    listen 443 ssl;
    server_name ${coreDomain};

    ssl_certificate     ${coreCrt};
    ssl_certificate_key ${coreKey};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;

    location / {
        proxy_pass http://opencom_core;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /gateway {
        proxy_pass http://opencom_core;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}

# Official Server Node (REST + WSS /gateway, voice, etc.)
server {
    listen 443 ssl;
    server_name ${nodeDomain};

    ssl_certificate     ${nodeCrt};
    ssl_certificate_key ${nodeKey};
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES256-GCM-SHA384:ECDHE-RSA-AES256-GCM-SHA384;

    location / {
        proxy_pass http://opencom_node;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location /gateway {
        proxy_pass http://opencom_node;
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
        proxy_read_timeout 86400;
        proxy_send_timeout 86400;
    }
}
`;
}

function main() {
  generateCerts();
  if (!certsOnly) {
    const config = nginxConfig();
    fs.writeFileSync(outputPath, config, "utf8");
    console.log(`[generate-nginx] Wrote ${path.relative(ROOT, outputPath)}`);
  }
  console.log("");
  console.log("Next steps:");
  console.log("  1. Add to /etc/hosts (if using .local):");
  console.log(`     127.0.0.1 ${coreDomain}`);
  console.log(`     127.0.0.1 ${nodeDomain}`);
  console.log("  2. In backend/.env set:");
  console.log(`     OFFICIAL_NODE_BASE_URL=https://${nodeDomain}`);
  console.log("  3. Include the generated config in nginx, e.g.:");
  console.log(`     include /path/to/OpenCom/nginx-opencom.conf;`);
  console.log("  4. Reload nginx: sudo nginx -t && sudo systemctl reload nginx");
}

main();
