export const BUILTIN_EMOTE_CATEGORIES = [
  {
    id: "smileys",
    label: "Smileys & Emotion",
    items: [
      { name: "grinning", value: "😀", aliases: ["grin"] },
      { name: "smiley", value: "😃" },
      { name: "smile", value: "😄" },
      { name: "beaming", value: "😁" },
      { name: "laughing", value: "😆" },
      { name: "sweat_smile", value: "😅" },
      { name: "joy", value: "😂", aliases: ["tears_of_joy"] },
      { name: "rofl", value: "🤣" },
      { name: "blush", value: "😊" },
      { name: "innocent", value: "😇" },
      { name: "wink", value: "😉" },
      { name: "relieved", value: "😌" },
      { name: "heart_eyes", value: "😍" },
      { name: "star_struck", value: "🤩" },
      { name: "kissing_heart", value: "😘" },
      { name: "yum", value: "😋" },
      { name: "stuck_out_tongue", value: "😛" },
      { name: "zany", value: "🤪" },
      { name: "sunglasses", value: "😎" },
      { name: "thinking", value: "🤔" },
      { name: "saluting", value: "🫡" },
      { name: "neutral_face", value: "😐" },
      { name: "expressionless", value: "😑" },
      { name: "smirk", value: "😏" },
      { name: "unamused", value: "😒" },
      { name: "roll_eyes", value: "🙄" },
      { name: "grimacing", value: "😬" },
      { name: "lying_face", value: "🤥" },
      { name: "shushing", value: "🤫" },
      { name: "melting", value: "🫠" },
      { name: "pleading", value: "🥺" },
      { name: "sad", value: "☹️", aliases: ["frowning"] },
      { name: "disappointed", value: "😞" },
      { name: "worried", value: "😟" },
      { name: "cry", value: "😢" },
      { name: "sob", value: "😭" },
      { name: "anguished", value: "😧" },
      { name: "scream", value: "😱" },
      { name: "flushed", value: "😳" },
      { name: "hot_face", value: "🥵" },
      { name: "cold_face", value: "🥶" },
      { name: "exploding_head", value: "🤯" },
      { name: "mind_blown", value: "🤯" },
      { name: "sleepy", value: "😪" },
      { name: "sleeping", value: "😴" },
      { name: "mask", value: "😷" },
      { name: "thermometer_face", value: "🤒" },
      { name: "head_bandage", value: "🤕" },
      { name: "nauseated", value: "🤢" },
      { name: "vomiting", value: "🤮" },
      { name: "dizzy_face", value: "😵" },
      { name: "skull", value: "💀" },
      { name: "alien", value: "👽" },
      { name: "robot", value: "🤖" },
      { name: "ghost", value: "👻" },
      { name: "poop", value: "💩" },
      { name: "clown", value: "🤡" },
      { name: "eyes", value: "👀" },
      { name: "zzz", value: "💤" },
    ],
  },
  {
    id: "hearts_hands",
    label: "Hearts & Hands",
    items: [
      { name: "heart", value: "❤️", aliases: ["red_heart"] },
      { name: "orange_heart", value: "🧡" },
      { name: "yellow_heart", value: "💛" },
      { name: "green_heart", value: "💚" },
      { name: "blue_heart", value: "💙" },
      { name: "purple_heart", value: "💜" },
      { name: "brown_heart", value: "🤎" },
      { name: "black_heart", value: "🖤" },
      { name: "white_heart", value: "🤍" },
      { name: "pink_heart", value: "🩷" },
      { name: "broken_heart", value: "💔" },
      { name: "two_hearts", value: "💕" },
      { name: "sparkling_heart", value: "💖" },
      { name: "heartpulse", value: "💗" },
      { name: "revolving_hearts", value: "💞" },
      { name: "cupid", value: "💘" },
      { name: "thumbs_up", value: "👍", aliases: ["+1", "thumbsup"] },
      { name: "thumbs_down", value: "👎", aliases: ["-1", "thumbsdown"] },
      { name: "clap", value: "👏" },
      { name: "wave", value: "👋" },
      { name: "raised_hands", value: "🙌" },
      { name: "pray", value: "🙏" },
      { name: "muscle", value: "💪" },
      { name: "ok_hand", value: "👌" },
      { name: "pinched_fingers", value: "🤌" },
      { name: "peace", value: "✌️", aliases: ["v"] },
      { name: "crossed_fingers", value: "🤞" },
      { name: "call_me", value: "🤙" },
      { name: "love_you", value: "🤟" },
      { name: "point_up", value: "☝️" },
      { name: "point_down", value: "👇" },
      { name: "point_left", value: "👈" },
      { name: "point_right", value: "👉" },
      { name: "fist", value: "✊" },
      { name: "punch", value: "👊" },
      { name: "handshake", value: "🤝" },
      { name: "writing_hand", value: "✍️" },
      { name: "nail_care", value: "💅" },
      { name: "ear", value: "👂" },
      { name: "nose", value: "👃" },
      { name: "brain", value: "🧠" },
    ],
  },
  {
    id: "animals_nature",
    label: "Animals & Nature",
    items: [
      { name: "sun", value: "☀️" },
      { name: "moon", value: "🌙" },
      { name: "star", value: "⭐" },
      { name: "sparkles", value: "✨" },
      { name: "zap", value: "⚡" },
      { name: "fire", value: "🔥" },
      { name: "droplet", value: "💧" },
      { name: "snowflake", value: "❄️" },
      { name: "rainbow", value: "🌈" },
      { name: "cloud", value: "☁️" },
      { name: "seedling", value: "🌱" },
      { name: "herb", value: "🌿" },
      { name: "four_leaf_clover", value: "🍀" },
      { name: "tree", value: "🌳" },
      { name: "palm_tree", value: "🌴" },
      { name: "cactus", value: "🌵" },
      { name: "rose", value: "🌹" },
      { name: "sunflower", value: "🌻" },
      { name: "hibiscus", value: "🌺" },
      { name: "cherry_blossom", value: "🌸" },
      { name: "tulip", value: "🌷" },
      { name: "mushroom", value: "🍄" },
      { name: "butterfly", value: "🦋" },
      { name: "bee", value: "🐝", aliases: ["honeybee"] },
      { name: "lady_beetle", value: "🐞" },
      { name: "bug", value: "🐛" },
      { name: "snail", value: "🐌" },
      { name: "turtle", value: "🐢" },
      { name: "dolphin", value: "🐬" },
      { name: "fish", value: "🐟" },
      { name: "tropical_fish", value: "🐠" },
      { name: "octopus", value: "🐙" },
      { name: "dog", value: "🐶" },
      { name: "cat", value: "🐱" },
      { name: "mouse", value: "🐭" },
      { name: "hamster", value: "🐹" },
      { name: "rabbit", value: "🐰" },
      { name: "fox", value: "🦊" },
      { name: "bear", value: "🐻" },
      { name: "panda", value: "🐼", aliases: ["panda_face"] },
      { name: "koala", value: "🐨" },
      { name: "tiger", value: "🐯" },
      { name: "lion", value: "🦁" },
      { name: "cow", value: "🐮" },
      { name: "pig", value: "🐷" },
      { name: "frog", value: "🐸" },
      { name: "monkey", value: "🐵", aliases: ["monkey_face"] },
      { name: "chicken", value: "🐔" },
      { name: "penguin", value: "🐧" },
      { name: "bird", value: "🐦" },
      { name: "duck", value: "🦆" },
      { name: "owl", value: "🦉" },
      { name: "unicorn", value: "🦄" },
    ],
  },
  {
    id: "food_drink",
    label: "Food & Drink",
    items: [
      { name: "apple", value: "🍎" },
      { name: "green_apple", value: "🍏" },
      { name: "tangerine", value: "🍊", aliases: ["orange"] },
      { name: "lemon", value: "🍋" },
      { name: "banana", value: "🍌" },
      { name: "watermelon", value: "🍉" },
      { name: "grapes", value: "🍇" },
      { name: "strawberry", value: "🍓" },
      { name: "blueberries", value: "🫐" },
      { name: "cherries", value: "🍒" },
      { name: "peach", value: "🍑" },
      { name: "pineapple", value: "🍍" },
      { name: "mango", value: "🥭" },
      { name: "avocado", value: "🥑" },
      { name: "eggplant", value: "🍆" },
      { name: "carrot", value: "🥕" },
      { name: "corn", value: "🌽" },
      { name: "hot_pepper", value: "🌶️" },
      { name: "croissant", value: "🥐" },
      { name: "bread", value: "🍞" },
      { name: "bagel", value: "🥯" },
      { name: "cheese", value: "🧀" },
      { name: "egg", value: "🥚" },
      { name: "bacon", value: "🥓" },
      { name: "hamburger", value: "🍔", aliases: ["burger"] },
      { name: "fries", value: "🍟" },
      { name: "pizza", value: "🍕" },
      { name: "hotdog", value: "🌭" },
      { name: "taco", value: "🌮" },
      { name: "burrito", value: "🌯" },
      { name: "sandwich", value: "🥪" },
      { name: "ramen", value: "🍜" },
      { name: "spaghetti", value: "🍝" },
      { name: "sushi", value: "🍣" },
      { name: "bento", value: "🍱" },
      { name: "curry", value: "🍛" },
      { name: "salad", value: "🥗" },
      { name: "popcorn", value: "🍿" },
      { name: "doughnut", value: "🍩" },
      { name: "cookie", value: "🍪" },
      { name: "birthday", value: "🎂" },
      { name: "cake", value: "🍰" },
      { name: "cupcake", value: "🧁" },
      { name: "icecream", value: "🍦" },
      { name: "coffee", value: "☕" },
      { name: "tea", value: "🍵" },
      { name: "bubble_tea", value: "🧋" },
      { name: "beer", value: "🍺" },
      { name: "beers", value: "🍻" },
      { name: "wine_glass", value: "🍷" },
      { name: "cocktail", value: "🍸" },
    ],
  },
  {
    id: "activities",
    label: "Activities & Fun",
    items: [
      { name: "soccer", value: "⚽" },
      { name: "basketball", value: "🏀" },
      { name: "football", value: "🏈" },
      { name: "baseball", value: "⚾" },
      { name: "tennis", value: "🎾" },
      { name: "volleyball", value: "🏐" },
      { name: "bowling", value: "🎳" },
      { name: "ping_pong", value: "🏓" },
      { name: "badminton", value: "🏸" },
      { name: "boxing_glove", value: "🥊" },
      { name: "dart", value: "🎯" },
      { name: "8ball", value: "🎱" },
      { name: "trophy", value: "🏆" },
      { name: "medal", value: "🏅" },
      { name: "crown", value: "👑" },
      { name: "gem", value: "💎" },
      { name: "100", value: "💯" },
      { name: "tada", value: "🎉" },
      { name: "confetti_ball", value: "🎊" },
      { name: "sparkler", value: "🎇" },
      { name: "fireworks", value: "🎆" },
      { name: "balloon", value: "🎈" },
      { name: "gift", value: "🎁" },
      { name: "tickets", value: "🎟️" },
      { name: "movie_camera", value: "🎥" },
      { name: "camera", value: "📷" },
      { name: "video_game", value: "🎮" },
      { name: "game_die", value: "🎲" },
      { name: "art", value: "🎨" },
      { name: "microphone", value: "🎤" },
      { name: "headphones", value: "🎧" },
      { name: "guitar", value: "🎸" },
      { name: "drum", value: "🥁" },
      { name: "musical_note", value: "🎵" },
      { name: "notes", value: "🎶" },
    ],
  },
  {
    id: "travel_places",
    label: "Travel & Places",
    items: [
      { name: "car", value: "🚗" },
      { name: "taxi", value: "🚕" },
      { name: "blue_car", value: "🚙" },
      { name: "bus", value: "🚌" },
      { name: "train", value: "🚆" },
      { name: "bullettrain", value: "🚅" },
      { name: "airplane", value: "✈️" },
      { name: "rocket", value: "🚀" },
      { name: "helicopter", value: "🚁" },
      { name: "sailboat", value: "⛵" },
      { name: "anchor", value: "⚓" },
      { name: "fuelpump", value: "⛽" },
      { name: "traffic_light", value: "🚦" },
      { name: "map", value: "🗺️" },
      { name: "compass", value: "🧭" },
      { name: "camping", value: "🏕️" },
      { name: "beach", value: "🏖️", aliases: ["beach_with_umbrella"] },
      { name: "mountain", value: "⛰️" },
      { name: "cityscape", value: "🏙️" },
      { name: "bridge_at_night", value: "🌉" },
      { name: "night_with_stars", value: "🌃" },
      { name: "house", value: "🏠" },
      { name: "office", value: "🏢" },
      { name: "school", value: "🏫" },
      { name: "stadium", value: "🏟️" },
      { name: "classical_building", value: "🏛️" },
    ],
  },
  {
    id: "objects_symbols",
    label: "Objects & Symbols",
    items: [
      { name: "laptop", value: "💻" },
      { name: "desktop", value: "🖥️" },
      { name: "keyboard", value: "⌨️" },
      { name: "mouse", value: "🖱️" },
      { name: "printer", value: "🖨️" },
      { name: "camera_flash", value: "📸" },
      { name: "phone", value: "📱", aliases: ["mobile_phone"] },
      { name: "telephone", value: "☎️" },
      { name: "battery", value: "🔋" },
      { name: "electric_plug", value: "🔌" },
      { name: "bulb", value: "💡" },
      { name: "flashlight", value: "🔦" },
      { name: "lock", value: "🔒" },
      { name: "unlock", value: "🔓" },
      { name: "key", value: "🔑" },
      { name: "hammer", value: "🔨" },
      { name: "wrench", value: "🔧" },
      { name: "gear", value: "⚙️" },
      { name: "toolbox", value: "🧰" },
      { name: "magnet", value: "🧲" },
      { name: "moneybag", value: "💰" },
      { name: "coin", value: "🪙" },
      { name: "credit_card", value: "💳" },
      { name: "envelope", value: "✉️" },
      { name: "email", value: "📧" },
      { name: "inbox_tray", value: "📥" },
      { name: "outbox_tray", value: "📤" },
      { name: "package", value: "📦" },
      { name: "bookmark", value: "🔖" },
      { name: "paperclip", value: "📎" },
      { name: "pushpin", value: "📌" },
      { name: "link", value: "🔗" },
      { name: "warning", value: "⚠️" },
      { name: "no_entry", value: "⛔" },
      { name: "check", value: "✅", aliases: ["check_mark"] },
      { name: "x", value: "❌" },
      { name: "question", value: "❓" },
      { name: "exclamation", value: "❗" },
      { name: "recycle", value: "♻️" },
      { name: "infinity", value: "♾️" },
    ],
  },
];

export const BUILTIN_EMOTE_ENTRIES = BUILTIN_EMOTE_CATEGORIES.flatMap(
  (category) =>
    category.items.map((item) => ({
      ...item,
      categoryId: category.id,
      categoryLabel: category.label,
      aliases: Array.isArray(item.aliases)
        ? item.aliases.map((alias) => String(alias).trim().toLowerCase()).filter(Boolean)
        : [],
    })),
);

export const BUILTIN_EMOTES = BUILTIN_EMOTE_ENTRIES.reduce((map, item) => {
  map[item.name] = item.value;
  for (const alias of item.aliases) {
    if (!map[alias]) map[alias] = item.value;
  }
  return map;
}, {});
